# Site settings
title: Leon Martin
description: PhD Student in Computational Neuroscience and Health Data Science
baseurl: "" 
#change the baseurl to "" if you are using it as your user GitHub Pages
url: "https://leon-k-martin.github.io"  


# GitHub User settings
username: Leon Martin
github_username: leon-k-martin
user_description: Knowledge-based systems, computational semantics, brain dynamics & network neuroscience
user_title: PhD Student
email: leon.martin@bih-charite.de

# Blog Author settings
author:
  googlescholar    : "https://scholar.google.com/citations?user=u2lL5j8AAAAJ&hl=en"
  name             : "Leon Martin"  
  email            : "leon.martin@bih-charite.de"
  github           : "http://github.com/leon-k-martin"


# markdown
markdown: kramdown
  
kramdown:
 footnote_nr: 1
 entity_output: as_char
 # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
 syntax_highlighter: rouge
 syntax_highlighter_opts:
  # Use existing pygments syntax highlighting css
  css_class: 'highlight'
 span:
  line_numbers: false
 block:
  line_numbers: true
  start_line: 1
 
highlighter: rouge
    
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  
permalink: none

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      toc: true
      mathjax: true
      mermaid: false
      highlight: false
      numbering: true
      status: Completed
      protected: false
      commentable: true
      rss: true
      numbering: true

exclude:
 - LICENSE.md
 - README.md
 - "*.cdf"
 - "*.nb"
 - "*.bk"
 - "*.draft.md"
