project:
  type: website
  output-dir: _site

website:
  title: "Leon Martin"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  page-footer:
    right:
      - icon: mastodon
        href: https://fediscience.org/@leonmartin


resources:
  - "public/*"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    include-in-header:
      - text: |
          <script src="//unpkg.com/react/umd/react.production.min.js"></script>
          <script src="//unpkg.com/react-dom/umd/react-dom.production.min.js"></script>
          <script src="//unpkg.com/@babel/standalone"></script>

          <script src="//unpkg.com/react-force-graph-2d"></script>
          <script src="//unpkg.com/3d-force-graph"></script>
          <script type="text/javascript" src="https://unpkg.com/vis-timeline@latest/standalone/umd/vis-timeline-graph2d.min.js"></script>
          <link href="https://unpkg.com/vis-timeline@latest/styles/vis-timeline-graph2d.min.css" rel="stylesheet" type="text/css" />

