# Curriculum Vitae

::: {.columns}

::: {.column}

## Contact Data

**Leon K. Martin**

Robert-Koch-Platz 4

10115 Berlin

E-Mail: leon.martin@bih-charite.de

Tel.: +49 30 450 560 813

:::
::: {.column}
## Personal Data

Date of birth: 12.06.1996

Place of birth: Nuremberg, Germany

Languages:

- German (native)
- English (fluent/C1-2)
:::
:::

## Education
```{=html}
<div id="visualization"></div>
<style>
  .vis-item .vis-item-overflow {
    overflow: visible;
  }
</style>
<script type="text/javascript">
  // DOM element where the Timeline will be attached
  var container = document.getElementById('visualization');

  // Create a DataSet (allows two way data-binding)
  var today = vis.moment(vis.moment.utc().format('YYYY-MM-DDT00:00:00.000Z'));
  var items = new vis.DataSet(
    [{
      "id": 1,
      "content": "Abitur (A-Levels)",
      "start": "2006-09-01",
      "end": "2014-06-30",
    },
    {
      "id": 2,
      "content": "B.Sc. Psychology",
      "start": "2014-10-01",
      "end": "2018-06-30",
    },
    {
      "id": 3,
      "content": "Bachelor Thesis",
      "start": "2018-06-30",
    },
    {
      "id": 4,
      "content": "M.Sc. Neuroscience",
      "start": "2018-10-01",
      "end": "2022-08-31",
    },
    {
      "id": 5,
      "content": "M.Sc. Clinical Psychology",
      "start": "2019-10-01",
      "end": today
    },
    {
      "id": 6,
      "content": "Master Thesis",
      "start": "2022-08-31",
    },
    {
      "id": 7,
      "content": "Graduand Student (Dr. rer. med.)",
      "start": "2023-01-18",
      "end": today
    }
  ]);

  // Configuration for the Timeline
  var options = {"end":"01-01-2030", "verticalScroll":"true", "zoomable":false, "verticalScroll":true};

  // Create a Timeline
  var timeline = new vis.Timeline(container, items, options);
</script>
```

2023 - **Graduand Student** (Dr. rer. med.) at Charité University
Medicine Berlin, Germany

2022 **Master thesis**: "*Mapping statistical search results from biomedical
knowledge discovery tools onto common brain parcellations*"
(Supervisors: Prof. Dr. Petra Ritter, Dr. Konstantin Bülau)

2019 - **Study of clinical psychology** (M.Sc.)

> Freie Universität Berlin \
> GPA: 1.2

2018 - 2022 **Study of neuroscience** (M.Sc.) at the Berlin School of
Mind and Brain

> Humboldt University Berlin, Germany \
> GPA: 1.0

2018 **Bachelor thesis**: "*The influence of instrumental music on the
implicit power motive and activity inhibition*" (Supervisor: Prof. Dr.
Oliver C. Schultheiss)

2014 - 2018 **Study of psychology** (B.Sc.)

> Friedrich-Alexander University Erlangen-Nürnberg, Germany \
> GPA: 1.2

2006 - 2014 Graduation: Abitur (A-Levels)

> Wolfram-von-Eschenbach Gymnasium in Schwabach, Germany \
> GPA: 1.0

## Work Experience

2021 - **Research Fellow**, Dept. Neurology, Brain Simulation Section

Berlin Institute of Health (BIH) / Charité University Medicine Berlin

2020 - 2021 **Student Research Assistant**, Dep. of Neurology, Brain
Simulation Section

> Charité University Medicine Berlin

2020 **Research Assistant**, Dep. of Neurology, Group: Music Evoked
Brain Plasticity

Max-Planck-Institute for Human Cognitive and Brain Sciences

2020 **Research Assistant**, Chair of German Linguistics (Dialectology)

Albert-Ludwigs-University Freiburg, Germany

2019 - 2020 **Research Internship**, Dep. Neurology, Group: Music Evoked
Brain Plasticity.

> Advisor: Dimitra Kandia, Tom Fritz
>
> Max-Planck-Institute for Human Cognitive and Brain Sciences, Leipzig,
> Germany

2019 - 2020 **Student Assistant**, Excellence Cluster NeuroCure &
Einstein Center for Neurosciences Berlin\
Charité University Medicine Berlin, Germany

2018 **Research Assistant** at the Chair of Psychological Diagnostics,
Differential and Personal Psychology\
Freie Universität Berlin, Germany

2016 - 2018 **Research Internship** at the Chair of Clinical Psychology
and Psychotherapy

Advisor: Christian Aljoscha Lukas

> Friedrich-Alexander-University Erlangen, Germany

2015 - 2017 **Student Research Assistant** at the Chair for Experimental
Psychology, Motivation and Affective Neuroscience

> Friedrich-Alexander University Erlangen, Germany

## Publications, First Authorships

Marti

## Publications, Co-Authorships

Stefanovski, L., Bülau, K., Martin, L., Courtiol, J., Diaz‐Cortes, M.
A., Langford, C., \... & Alzheimer's Disease Neuroimaging Initiative.
(2021). Spatial mapping of subcellular disease pathways and
cytoarchitecture to anatomical brain regions for multi‐scale brain
simulation with The Virtual Brain. *Alzheimer\'s & Dementia*, *17*,
e052311.

Stefanovski, L., Meier, J. M., Pai, R. K., Triebkorn, P., Lett, T.,
**Martin, L**., Bülau, K., Hofmann-Apitius, M., Solodkin, A., McIntosh,
A. R., & Ritter, P. (2021). Bridging Scales in Alzheimer's Disease:
Biological Framework for Brain Simulation with The Virtual Brain.
*Frontiers in Neuroinformatics*, 15(April), 1--30.
<https://doi.org/10.3389/fninf.2021.630172>

Schultheiss, O. C., Frisch, M., Özbe, D., Ossmann, A., Schultheiss, M.,
Lentz, S., **Martin, L**., & Rösch, A. G. (2019). Implicit motives show
sex-dimorphic associations with digit ratio. *Motivation Science*, 5(4),
326--342. <https://doi.org/10.1037/mot0000122>

## Poster Presentations

Martin L., Stefanovski L., Bülau Konstantin, Kodamullil A. T., Jacobs M,
Hofmann-Apitius M. (2022). Decoding spatial patterns of amyloid-beta PET
using TVBase -- a tool for mapping biological knowledge onto a 3D brain
atlas. SfN Neuroscience 2022, 11.15., San Diego

## Lectures

Sep. 2022 The Virtual Brain in Clinical Research (Summer School 2022)
\[[YouTube](https://youtu.be/QhbIVgjjgqc)\]

## Talks/Workshops

May 2021 Young Researchers Event 2021 -- EBRAINS for next-generation
brain medicine
\[[link](https://www.brainsimulation.org/bsw/zwei/events/single/6931-young-researchers-event-2021-ebrains-for-next-generation-brain-medicine)\]

June 2021 McGill Summer School: The Virtual Brain lecture and workshop
\[[link](https://www.brainsimulation.org/bsw/zwei/events/single/6751-mcgill-summer-school-the-virtual-brain-lecture-and-workshop)\]

June 2021 TVB-EBRAINS Integrated Workflows - 5th Virtual Workshop
\[[link](https://www.brainsimulation.org/bsw/zwei/events/single/7021-tvb-ebrains-integrated-workflows-5th-workshop)\]

March 2021 TVB-EBRAINS Integrated Workflows - 4th Workshop
\[[link](https://www.brainsimulation.org/bsw/zwei/events/single/6571-tvb-ebrains-integrated-workflows-4th-virtual-workshop)\]

Jan. 2021 Virtual Course "Personalized Multi-Scale Brain Simulation"
[\[link\]](https://www.brainsimulation.org/bsw/zwei/events/single/6202--personalized-multi-scale-brain-simulation-virtual-course-from-dec-3-2020-to-feb-18-2021)

## Certifications

##

-   Certified assistant for trauma therapy with refugee children and
    adolescents (Festland e.V.)

-   Certified coder for implicit achievement, affiliation, and power
    motivation \[According to Winter, 1994\] with extensive coding
    experience (\>3000 PSEs scored)

## Social Engagement

##

2021 Youth work

Zentrum ÜBERLEBEN, Berlin

2020 Trauma therapy for children and adolescents with experiences of
displacement

> Festland e.V.

2020 - Acute drug emergency aid, psycho-social support, and
psychoeducation

> Eclipse e.V., Berlin

Berlin, January 26, 2023 Leon Martin
